language: python
python:
  - "3.6"
sudo: false

env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest

branches:
  only:
    - master

install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C bin
  - export PATH=$(pwd)/bin:$PATH
  - make ci-env

script:
  - make ci-test
